### ISSUE TITLE
Gradle Project로 변환

### ISSUE THREAD

**Issue by horace-velmont** [ICT-Heroes/Hyperion#6]
프로젝트 내의 task-dialog-1.3.5.jar 및 miglayout-3.7.2.zip은 로컬 의존성으로 집어넣고
그외 Junit는 외부 의존성으로 하는 Gradle 프로젝트 변환 작업

**Comment by horace-velmont** [comment]
이거 취소하기로 했나

**Comment by NakOh** [comment]
취소. 무의미.
